#!/bin/bash

#`git clean` doesn't currently respect submodule.recurse,
# but, for all we know, when Git adds support for this,
# it'll cause redundant traversal
# (as is the current (v2.29) situation with `fetch`).
#So we disable it.

git -c submodule.recurse=0 clean -xffd

git -c submodule.recurse=0 submodule foreach --recursive --quiet git -c submodule.recurse=0 clean -xffd

